let testData = {
  pool1: {
    sets: [
      {
        id: '4136651',
        tag: 'HD',
      },
      {
        id: '4316801',
        tag: 'HD',
      },
      {
        id: '3953694',
        tag: 'HD',
      },
      {
        id: '3379930',
        tag: 'HD',
      },
      {
        id: '4149857',
        tag: 'HD',
      },
      {
        id: '1867710',
        tag: 'HD',
      },
      {
        id: '3454421',
        tag: 'NM',
      },
      {
        id: '4192224',
        tag: 'NM',
      },
      {
        id: '753081',
        tag: 'DT',
      },
      {
        id: '4059927',
        tag: 'DT',
      },
      {
        id: '4117349',
        tag: 'FM',
      },
      {
        id: '3396582',
        tag: 'FM',
      },
      {
        id: '3669469',
        tag: 'FM',
      },
      {
        id: '4434604',
        tag: 'TB',
      },
    ],
    data: [
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4136651,
          beatmapset_id: 1876690,
          user_id: 1974436,
          version: "Habi's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.9,
          mode_int: 0,
          ar: 9,
          cs: 4.2,
          od: 8,
          hp: 5,
          hit_length: 247,
          total_length: 273,
          count_circles: 378,
          count_sliders: 478,
          count_spinners: 3,
          beatmapset: {
            id: 1876690,
            user_id: 3222353,
            ranked: 1,
            creator: 'Sarawatlism',
            artist: 'nao feat. isui',
            artist_unicode: '夏央 feat. 倚水',
            title: 'Summer Lights',
            title_unicode: 'サマーライト',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.9,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4316801,
          beatmapset_id: 2063899,
          user_id: 2123087,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.62,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 4.5,
          hit_length: 115,
          total_length: 115,
          count_circles: 299,
          count_sliders: 185,
          count_spinners: 1,
          beatmapset: {
            id: 2063899,
            user_id: 2123087,
            ranked: 1,
            creator: 'hehe',
            artist: 'II-L',
            artist_unicode: 'II-L',
            title: 'V804N (BMS Edit)',
            title_unicode: 'V804N (BMS Edit)',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.62,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3953694,
          beatmapset_id: 1916172,
          user_id: 10820856,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.36,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8.5,
          hp: 5,
          hit_length: 211,
          total_length: 219,
          count_circles: 506,
          count_sliders: 310,
          count_spinners: 0,
          beatmapset: {
            id: 1916172,
            user_id: 10820856,
            ranked: 1,
            creator: 'Shirahane Suou',
            artist: 'kessoku band',
            artist_unicode: '結束バンド',
            title: 'Nani ga Warui',
            title_unicode: 'なにが悪い',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.36,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3379930,
          beatmapset_id: 1649315,
          user_id: 8972308,
          version: "ScubDomino's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.9,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 201,
          total_length: 259,
          count_circles: 337,
          count_sliders: 291,
          count_spinners: 0,
          beatmapset: {
            id: 1649315,
            user_id: 171021,
            ranked: 1,
            creator: 'Beren',
            artist: 'Sheena Ringo',
            artist_unicode: '椎名林檎',
            title: 'Yami ni Furu Ame',
            title_unicode: '闇に降る雨',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.9,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4149857,
          beatmapset_id: 1994520,
          user_id: 13947939,
          version: "pnky's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.94,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 154,
          total_length: 159,
          count_circles: 294,
          count_sliders: 298,
          count_spinners: 0,
          beatmapset: {
            id: 1994520,
            user_id: 6055351,
            ranked: 1,
            creator: 'gazimal',
            artist: 'DECO*27',
            artist_unicode: 'DECO*27',
            title: 'Mannequin feat. Hatsune Miku',
            title_unicode: 'マネキン feat. 初音ミク',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.94,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 1867710,
          beatmapset_id: 893725,
          user_id: 4696296,
          version: 'Other Self',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.31,
          mode_int: 0,
          ar: 8.6,
          cs: 4,
          od: 7.4,
          hp: 5,
          hit_length: 209,
          total_length: 219,
          count_circles: 368,
          count_sliders: 278,
          count_spinners: 1,
          beatmapset: {
            id: 893725,
            user_id: 4696296,
            ranked: 1,
            creator: 'celerih',
            artist: 'Sally',
            artist_unicode: 'サリー',
            title: 'did -Less Extra- Ranko ver.',
            title_unicode: 'did -Less Extra- ランコver.',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.31,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3454421,
          beatmapset_id: 1676960,
          user_id: 6984103,
          version: "Kuse's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.84,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 200,
          total_length: 208,
          count_circles: 337,
          count_sliders: 389,
          count_spinners: 0,
          beatmapset: {
            id: 1676960,
            user_id: 13102983,
            ranked: 1,
            creator: 'Irin',
            artist: 'Harumaki Gohan feat. Hatsune Miku',
            artist_unicode: 'はるまきごはん feat. 初音ミク',
            title: 'Hotaru wa Inakatta',
            title_unicode: '蛍はいなかった',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 4.84,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4192224,
          beatmapset_id: 2014469,
          user_id: 12469536,
          version: 'collab lunatic',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.61,
          mode_int: 0,
          ar: 8.5,
          cs: 4,
          od: 8.5,
          hp: 4,
          hit_length: 143,
          total_length: 152,
          count_circles: 396,
          count_sliders: 162,
          count_spinners: 1,
          beatmapset: {
            id: 2014469,
            user_id: 12366071,
            ranked: 1,
            creator: 'nanoya',
            artist: 'Down',
            artist_unicode: 'Down',
            title: 'nanoya',
            title_unicode: 'nanoya',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 4.61,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 753081,
          beatmapset_id: 340444,
          user_id: 3323762,
          version: 'Saranghae',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.67,
          mode_int: 0,
          ar: 8,
          cs: 4,
          od: 7,
          hp: 6.5,
          hit_length: 185,
          total_length: 190,
          count_circles: 276,
          count_sliders: 237,
          count_spinners: 0,
          beatmapset: {
            id: 340444,
            user_id: 3323762,
            ranked: 1,
            creator: 'Aerous',
            artist: 'AOA',
            artist_unicode: 'AOA',
            title: 'Heart Attack',
            title_unicode: '심쿵해',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 5.04,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4059927,
          beatmapset_id: 1959309,
          user_id: 7742067,
          version: "spoken's Hard",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.5,
          mode_int: 0,
          ar: 8,
          cs: 4,
          od: 7,
          hp: 5,
          hit_length: 217,
          total_length: 235,
          count_circles: 323,
          count_sliders: 356,
          count_spinners: 0,
          beatmapset: {
            id: 1959309,
            user_id: 1661227,
            ranked: 1,
            creator: 'Satellite',
            artist: 'senya',
            artist_unicode: 'senya',
            title: 'Kimiiro Subliminal',
            title_unicode: '君色サブリミナル',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 4.83,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4117349,
          beatmapset_id: 1981110,
          user_id: 6220419,
          version: "Nakazawa Sensei's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.79,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 4.5,
          hit_length: 127,
          total_length: 127,
          count_circles: 289,
          count_sliders: 228,
          count_spinners: 1,
          beatmapset: {
            id: 1981110,
            user_id: 16429579,
            ranked: 1,
            creator: 'Stompy_',
            artist: 'Mitsukiyo',
            artist_unicode: 'ミツキヨ',
            title: 'Future Bossa',
            title_unicode: 'Future Bossa',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 4.79,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3396582,
          beatmapset_id: 1631947,
          user_id: 2556958,
          version: "ReaL's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.79,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 110,
          total_length: 111,
          count_circles: 266,
          count_sliders: 269,
          count_spinners: 1,
          beatmapset: {
            id: 1631947,
            user_id: 1574070,
            ranked: 1,
            creator: 'Kloyd',
            artist: 'KUMOKIRI',
            artist_unicode: 'KUMOKIRI',
            title: 'Shippuujinrai',
            title_unicode: '疾風迅雷',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 4.79,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3669469,
          beatmapset_id: 1160351,
          user_id: 3087506,
          version: "JeZag's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.95,
          mode_int: 0,
          ar: 9,
          cs: 3,
          od: 7.5,
          hp: 4,
          hit_length: 129,
          total_length: 147,
          count_circles: 297,
          count_sliders: 213,
          count_spinners: 4,
          beatmapset: {
            id: 1160351,
            user_id: 8352623,
            ranked: 1,
            creator: 'Fisky',
            artist: 'Chroma',
            artist_unicode: '黒魔',
            title: 'Destroy, Destroy, Destroy The Happy End (Cut Ver.)',
            title_unicode: 'Destroy, Destroy, Destroy The Happy End (Cut Ver.)',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: true,
        star: 4.95,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4434604,
          beatmapset_id: 2108981,
          user_id: 896613,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.11,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 356,
          total_length: 392,
          count_circles: 854,
          count_sliders: 658,
          count_spinners: 0,
          beatmapset: {
            id: 2108981,
            user_id: 896613,
            ranked: 1,
            creator: 'Lasse',
            artist: 'Yousei Teikoku',
            artist_unicode: '妖精帝國',
            title: 'Ira',
            title_unicode: 'Ira',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'TB',
        isLast: true,
        star: 5.11,
      },
    ],
    status: {
      isLoading: false,
      title: 'YHC S4 淘汰赛第一轮图池',
    },
    src: 'HD 4136651 4316801 3953694 3379930 4149857 1867710 NM 3454421 4192224 DT 753081 4059927 FM 4117349 3396582 3669469 TB 4434604',
  },
  pool2: {
    sets: [
      {
        id: '3295947',
        tag: 'HD',
      },
      {
        id: '3535432',
        tag: 'HD',
      },
      {
        id: '2892338',
        tag: 'HD',
      },
      {
        id: '2434770',
        tag: 'HD',
      },
      {
        id: '4313545',
        tag: 'HD',
      },
      {
        id: '4253149',
        tag: 'HD',
      },
      {
        id: '3794164',
        tag: 'NM',
      },
      {
        id: '2278423',
        tag: 'NM',
      },
      {
        id: '3334117',
        tag: 'DT',
      },
      {
        id: '4362204',
        tag: 'DT',
      },
      {
        id: '2273016',
        tag: 'FM',
      },
      {
        id: '2794470',
        tag: 'FM',
      },
      {
        id: '4093505',
        tag: 'FM',
      },
      {
        id: '1968981',
        tag: 'TB',
      },
    ],
    data: [
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3295947,
          beatmapset_id: 1614390,
          user_id: 3545323,
          version: 'smile',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.18,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8.8,
          hp: 6,
          hit_length: 223,
          total_length: 229,
          count_circles: 610,
          count_sliders: 312,
          count_spinners: 1,
          beatmapset: {
            id: 1614390,
            user_id: 3545323,
            ranked: 1,
            creator: 'alden',
            artist: 'Momokurotei Ichimon',
            artist_unicode: '桃黒亭一門',
            title: 'Nippon Egao Hyakkei',
            title_unicode: 'ニッポン笑顔百景',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.18,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3535432,
          beatmapset_id: 1690826,
          user_id: 3109248,
          version: "lit120's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.16,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 7,
          hp: 6,
          hit_length: 168,
          total_length: 190,
          count_circles: 456,
          count_sliders: 245,
          count_spinners: 4,
          beatmapset: {
            id: 1690826,
            user_id: 7451883,
            ranked: 1,
            creator: 'Nevo',
            artist: 'Natsume Chiaki',
            artist_unicode: 'なつめ千秋',
            title: 'Hanairo Biyori',
            title_unicode: '花色日和',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.16,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2892338,
          beatmapset_id: 1352063,
          user_id: 10630389,
          version: "Fish Rose's Insane",
          ranked: -2,
          status: 'graveyard',
          difficulty_rating: 4.48,
          mode_int: 0,
          ar: 9,
          cs: 3.8,
          od: 7,
          hp: 6,
          hit_length: 186,
          total_length: 200,
          count_circles: 407,
          count_sliders: 376,
          count_spinners: 0,
          beatmapset: {
            id: 1352063,
            user_id: 13102983,
            ranked: -2,
            creator: 'Irin',
            artist: 'RuLu feat. Youi',
            artist_unicode: 'RuLu feat. よーい',
            title: 'Xylophone',
            title_unicode: 'シロフォン',
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.48,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2434770,
          beatmapset_id: 1166409,
          user_id: 896613,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.02,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 6,
          hit_length: 232,
          total_length: 248,
          count_circles: 430,
          count_sliders: 446,
          count_spinners: 1,
          beatmapset: {
            id: 1166409,
            user_id: 896613,
            ranked: 1,
            creator: 'Lasse',
            artist: 'Shimotsuki Haruka',
            artist_unicode: '霜月はるか',
            title: 'Tooryanse',
            title_unicode: '通りゃんせ',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.02,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4313545,
          beatmapset_id: 2062538,
          user_id: 9590557,
          version: "Firika's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.08,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 117,
          total_length: 123,
          count_circles: 257,
          count_sliders: 196,
          count_spinners: 3,
          beatmapset: {
            id: 2062538,
            user_id: 4564285,
            ranked: 1,
            creator: 'Ascended',
            artist: 'Amuro vs. Killer',
            artist_unicode: 'Amuro vs. Killer',
            title: 'Mei',
            title_unicode: '冥',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.08,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4253149,
          beatmapset_id: 2039084,
          user_id: 4414426,
          version: 'Sakura',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.72,
          mode_int: 0,
          ar: 8,
          cs: 4.5,
          od: 7,
          hp: 7,
          hit_length: 102,
          total_length: 112,
          count_circles: 289,
          count_sliders: 89,
          count_spinners: 14,
          beatmapset: {
            id: 2039084,
            user_id: 4414426,
            ranked: 1,
            creator: '-Ady',
            artist: 'Silver Forest',
            artist_unicode: 'Silver Forest',
            title: 'Sora ni Mae, Sumizome no Sakura (Cut Ver.)',
            title_unicode: '蒼空に舞え、墨染の桜 (Cut Ver.)',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.72,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3794164,
          beatmapset_id: 1614761,
          user_id: 11839745,
          version: "Voice's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.01,
          mode_int: 0,
          ar: 9,
          cs: 3.9,
          od: 8.1,
          hp: 4.9,
          hit_length: 183,
          total_length: 198,
          count_circles: 359,
          count_sliders: 311,
          count_spinners: 2,
          beatmapset: {
            id: 1614761,
            user_id: 13102983,
            ranked: 1,
            creator: 'Surou',
            artist: 'onoken',
            artist_unicode: 'onoken',
            title: 'F-mine',
            title_unicode: 'F-mine',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 5.01,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2278423,
          beatmapset_id: 1084284,
          user_id: 4673089,
          version: "Impwari's Insane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.06,
          mode_int: 0,
          ar: 9,
          cs: 4.3,
          od: 8,
          hp: 6,
          hit_length: 187,
          total_length: 200,
          count_circles: 448,
          count_sliders: 322,
          count_spinners: 0,
          beatmapset: {
            id: 1084284,
            user_id: 4673089,
            ranked: 1,
            creator: 'Black Man',
            artist: 'hitorie',
            artist_unicode: 'ヒトリエ',
            title: 'One Me Two Hearts',
            title_unicode: 'ワンミーツハー',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 5.06,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3334117,
          beatmapset_id: 1633475,
          user_id: 9254241,
          version: "Alex's Hard",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.66,
          mode_int: 0,
          ar: 8,
          cs: 4,
          od: 6,
          hp: 5,
          hit_length: 231,
          total_length: 234,
          count_circles: 410,
          count_sliders: 344,
          count_spinners: 3,
          beatmapset: {
            id: 1633475,
            user_id: 700887,
            ranked: 1,
            creator: 'Sekai',
            artist: 'Inori Minase',
            artist_unicode: '水瀬いのり',
            title: 'Snow White',
            title_unicode: 'Snow White',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 5.1,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4362204,
          beatmapset_id: 1867887,
          user_id: 7003013,
          version: "Muz's Hard",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.58,
          mode_int: 0,
          ar: 8,
          cs: 3.5,
          od: 6.5,
          hp: 4,
          hit_length: 128,
          total_length: 138,
          count_circles: 176,
          count_sliders: 251,
          count_spinners: 0,
          beatmapset: {
            id: 1867887,
            user_id: 416662,
            ranked: 1,
            creator: 'Hollow Wings',
            artist: 'A.SAKA',
            artist_unicode: 'A.SAKA',
            title: 'Nanatsu Momijiakari',
            title_unicode: '七つ紅葉灯',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 5.14,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2273016,
          beatmapset_id: 1086990,
          user_id: 1470352,
          version: 'Lunatic',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.95,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 7,
          hit_length: 183,
          total_length: 184,
          count_circles: 304,
          count_sliders: 374,
          count_spinners: 2,
          beatmapset: {
            id: 1086990,
            user_id: 1470352,
            ranked: 1,
            creator: 'Trust',
            artist: 'Dark PHOENiX',
            artist_unicode: 'Dark PHOENiX',
            title: 'Shunshun Shuugetsu',
            title_unicode: '蠢々秋月',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 4.95,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2794470,
          beatmapset_id: 1269063,
          user_id: 4334976,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.1,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5.5,
          hit_length: 135,
          total_length: 145,
          count_circles: 334,
          count_sliders: 216,
          count_spinners: 1,
          beatmapset: {
            id: 1269063,
            user_id: 4334976,
            ranked: 1,
            creator: 'Aeril',
            artist: 'ginkiha',
            artist_unicode: 'ginkiha',
            title: 'EOS',
            title_unicode: 'EOS',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 5.1,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4093505,
          beatmapset_id: 1972749,
          user_id: 14339830,
          version: 'Collab Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.04,
          mode_int: 0,
          ar: 9,
          cs: 3.7,
          od: 8,
          hp: 5,
          hit_length: 145,
          total_length: 145,
          count_circles: 398,
          count_sliders: 299,
          count_spinners: 1,
          beatmapset: {
            id: 1972749,
            user_id: 3906405,
            ranked: 1,
            creator: 'Sylas',
            artist: 'James Landino',
            artist_unicode: 'James Landino',
            title: "Aresene's Bazaar",
            title_unicode: "Aresene's Bazaar",
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: true,
        star: 5.04,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 1968981,
          beatmapset_id: 942849,
          user_id: 7322726,
          version: 'Lament',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.37,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 6,
          hit_length: 320,
          total_length: 320,
          count_circles: 656,
          count_sliders: 487,
          count_spinners: 1,
          beatmapset: {
            id: 942849,
            user_id: 7322726,
            ranked: 1,
            creator: 'lcfc',
            artist: 'Chata',
            artist_unicode: '茶太',
            title: 'Nocte of desperatio',
            title_unicode: 'Nocte of desperatio',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'TB',
        isLast: true,
        star: 5.37,
      },
    ],
    status: {
      isLoading: false,
      title: 'YHC S4 淘汰赛第二轮图池',
    },
    src: 'HD 3295947 3535432 2892338 2434770 4313545 4253149 NM 3794164 2278423 DT 3334117 4362204 FM 2273016 2794470 4093505 TB 1968981',
  },
  pool3: {
    sets: [
      {
        id: '4230631',
        tag: 'HD',
      },
      {
        id: '4055401',
        tag: 'HD',
      },
      {
        id: '4118513',
        tag: 'HD',
      },
      {
        id: '4507262',
        tag: 'HD',
      },
      {
        id: '4282790',
        tag: 'HD',
      },
      {
        id: '4267493',
        tag: 'HD',
      },
      {
        id: '4323255',
        tag: 'HD',
      },
      {
        id: '2979825',
        tag: 'NM',
      },
      {
        id: '3489502',
        tag: 'NM',
      },
      {
        id: '3763548',
        tag: 'DT',
      },
      {
        id: '3512086',
        tag: 'DT',
      },
      {
        id: '4281786',
        tag: 'DT',
      },
      {
        id: '4263552',
        tag: 'FM',
      },
      {
        id: '4183276',
        tag: 'FM',
      },
      {
        id: '4241261',
        tag: 'FM',
      },
      {
        id: '3069278',
        tag: 'TB',
      },
    ],
    data: [
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4230631,
          beatmapset_id: 2030184,
          user_id: 5210848,
          version: "Wen's Expert",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.36,
          mode_int: 0,
          ar: 9,
          cs: 3.8,
          od: 8.5,
          hp: 5.2,
          hit_length: 257,
          total_length: 275,
          count_circles: 702,
          count_sliders: 312,
          count_spinners: 1,
          beatmapset: {
            id: 2030184,
            user_id: 7326908,
            ranked: 1,
            creator: 'Amateurre',
            artist: 'ClariS',
            artist_unicode: 'ClariS',
            title: 'Koi Sekai',
            title_unicode: 'コイセカイ',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.36,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4055401,
          beatmapset_id: 1957515,
          user_id: 6854920,
          version: 'Breeze',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.39,
          mode_int: 0,
          ar: 9.2,
          cs: 4,
          od: 8,
          hp: 6,
          hit_length: 111,
          total_length: 112,
          count_circles: 402,
          count_sliders: 238,
          count_spinners: 1,
          beatmapset: {
            id: 1957515,
            user_id: 7075821,
            ranked: 1,
            creator: 'Sphaela',
            artist: '69 de 74',
            artist_unicode: '69 de 74',
            title: 'Holy Wind',
            title_unicode: 'Holy Wind',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.39,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4118513,
          beatmapset_id: 1760668,
          user_id: 2688103,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.82,
          mode_int: 0,
          ar: 9,
          cs: 3.8,
          od: 7.5,
          hp: 6,
          hit_length: 225,
          total_length: 226,
          count_circles: 446,
          count_sliders: 539,
          count_spinners: 5,
          beatmapset: {
            id: 1760668,
            user_id: 2688103,
            ranked: 1,
            creator: 'IOException',
            artist: 'lapix',
            artist_unicode: 'lapix',
            title: 'Day by Day feat. Nicole Curry',
            title_unicode: 'Day by Day feat. Nicole Curry',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 4.82,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4507262,
          beatmapset_id: 2141428,
          user_id: 1814662,
          version: 'HD Lover',
          ranked: -2,
          status: 'graveyard',
          difficulty_rating: 5.35,
          mode_int: 0,
          ar: 9.2,
          cs: 4.2,
          od: 8,
          hp: 5,
          hit_length: 185,
          total_length: 203,
          count_circles: 508,
          count_sliders: 283,
          count_spinners: 1,
          beatmapset: {
            id: 2141428,
            user_id: 1814662,
            ranked: -2,
            creator: 'X Light',
            artist: 'Shiina Ringo',
            artist_unicode: '椎名林檎',
            title: 'Netsuai Hakkakuchu',
            title_unicode: '熱愛発覚中',
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.35,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4282790,
          beatmapset_id: 2008761,
          user_id: 2490770,
          version: 'Expert',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.46,
          mode_int: 0,
          ar: 9,
          cs: 4,
          od: 8,
          hp: 5,
          hit_length: 140,
          total_length: 144,
          count_circles: 475,
          count_sliders: 265,
          count_spinners: 1,
          beatmapset: {
            id: 2008761,
            user_id: 2490770,
            ranked: 1,
            creator: 'Cellina',
            artist: 'TJ.hangneil',
            artist_unicode: 'TJ.hangneil',
            title: 'Kamui',
            title_unicode: '神威',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.46,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4267493,
          beatmapset_id: 2044626,
          user_id: 6055351,
          version: "gazimal's x",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.43,
          mode_int: 0,
          ar: 9.4,
          cs: 4,
          od: 8.8,
          hp: 5,
          hit_length: 171,
          total_length: 187,
          count_circles: 215,
          count_sliders: 454,
          count_spinners: 1,
          beatmapset: {
            id: 2044626,
            user_id: 9327302,
            ranked: 1,
            creator: 'SMOKELIND',
            artist: 'C-Show',
            artist_unicode: 'C-Show',
            title: 'AImee feat. Aitsuki Nakuru',
            title_unicode: 'AImee feat. 藍月なくる',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: false,
        star: 5.43,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4323255,
          beatmapset_id: 2066498,
          user_id: 1233255,
          version: "PandaHero's Kuru-kurunatic",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.99,
          mode_int: 0,
          ar: 8,
          cs: 4,
          od: 8,
          hp: 6,
          hit_length: 178,
          total_length: 196,
          count_circles: 596,
          count_sliders: 134,
          count_spinners: 1,
          beatmapset: {
            id: 2066498,
            user_id: 4960893,
            ranked: 1,
            creator: 'Djulus',
            artist: 'IOSYS',
            artist_unicode: 'IOSYS',
            title: 'Miracle Hinacle',
            title_unicode: 'Miracle∞Hinacle',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'HD',
        isLast: true,
        star: 4.99,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 2979825,
          beatmapset_id: 1431969,
          user_id: 11443437,
          version: 'Lunatic',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.32,
          mode_int: 0,
          ar: 9,
          cs: 3.7,
          od: 8,
          hp: 5,
          hit_length: 214,
          total_length: 216,
          count_circles: 473,
          count_sliders: 385,
          count_spinners: 1,
          beatmapset: {
            id: 1431969,
            user_id: 11443437,
            ranked: 1,
            creator: '[Karcher]',
            artist: 'Foreground Eclipse',
            artist_unicode: 'Foreground Eclipse',
            title: 'Dear, Are You Getting Sober',
            title_unicode: 'Dear, Are You Getting Sober',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 5.32,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3489502,
          beatmapset_id: 1707712,
          user_id: 1243669,
          version: 'Expert',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.32,
          mode_int: 0,
          ar: 9,
          cs: 4.5,
          od: 8.7,
          hp: 6,
          hit_length: 115,
          total_length: 115,
          count_circles: 394,
          count_sliders: 158,
          count_spinners: 0,
          beatmapset: {
            id: 1707712,
            user_id: 1243669,
            ranked: 1,
            creator: 'yf_bmp',
            artist: 'Qrispy Joybox feat. Yu Tokiwa',
            artist_unicode: 'Qrispy Joybox feat. 常盤ゆう',
            title: 'Shiratsuyu no Kaze',
            title_unicode: '白露の風',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'NM',
        isLast: false,
        star: 5.32,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3763548,
          beatmapset_id: 1449452,
          user_id: 1623405,
          version: 'Hard',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.83,
          mode_int: 0,
          ar: 8,
          cs: 3.8,
          od: 6,
          hp: 4,
          hit_length: 257,
          total_length: 264,
          count_circles: 559,
          count_sliders: 276,
          count_spinners: 2,
          beatmapset: {
            id: 1449452,
            user_id: 1623405,
            ranked: 1,
            creator: 'Okoratu',
            artist: 'Hatsuki Yura',
            artist_unicode: '葉月ゆら',
            title: 'Secret Rose Garden',
            title_unicode: 'Secret Rose Garden',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 3.83,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3512086,
          beatmapset_id: 1678673,
          user_id: 16080485,
          version: "Sanayui's Hard",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 3.93,
          mode_int: 0,
          ar: 8,
          cs: 3.3,
          od: 6.2,
          hp: 4.6,
          hit_length: 239,
          total_length: 259,
          count_circles: 366,
          count_sliders: 353,
          count_spinners: 0,
          beatmapset: {
            id: 1678673,
            user_id: 1844862,
            ranked: 1,
            creator: 'MianYa',
            artist: 'ClariS',
            artist_unicode: 'ClariS',
            title: 'border',
            title_unicode: 'border',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: false,
        star: 3.93,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4281786,
          beatmapset_id: 2050540,
          user_id: 15823344,
          version: "Collab I'nsane",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 4.01,
          mode_int: 0,
          ar: 8.4,
          cs: 4.5,
          od: 7.5,
          hp: 4.5,
          hit_length: 156,
          total_length: 171,
          count_circles: 177,
          count_sliders: 289,
          count_spinners: 0,
          beatmapset: {
            id: 2050540,
            user_id: 16429579,
            ranked: 1,
            creator: 'Stompy_',
            artist: 'beignet',
            artist_unicode: 'beignet',
            title: "S'more",
            title_unicode: "S'more",
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'DT',
        isLast: true,
        star: 4.01,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4263552,
          beatmapset_id: 2037770,
          user_id: 4754771,
          version: 'Another',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.31,
          mode_int: 0,
          ar: 9.2,
          cs: 3.2,
          od: 8.5,
          hp: 5.8,
          hit_length: 256,
          total_length: 257,
          count_circles: 555,
          count_sliders: 436,
          count_spinners: 0,
          beatmapset: {
            id: 2037770,
            user_id: 4754771,
            ranked: 1,
            creator: 'Akitoshi',
            artist: 'SILENT SIREN',
            artist_unicode: 'SILENT SIREN',
            title: 'Hachigatsu no Yoru',
            title_unicode: '八月の夜',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 5.31,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4183276,
          beatmapset_id: 1997883,
          user_id: 3223044,
          version: "Skymin's Extra",
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.32,
          mode_int: 0,
          ar: 9.4,
          cs: 4,
          od: 9,
          hp: 5,
          hit_length: 199,
          total_length: 199,
          count_circles: 400,
          count_sliders: 417,
          count_spinners: 2,
          beatmapset: {
            id: 1997883,
            user_id: 3181083,
            ranked: 1,
            creator: 'AJT',
            artist: 'Red Velvet',
            artist_unicode: '레드벨벳',
            title: 'Power Up',
            title_unicode: 'Power Up',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: false,
        star: 5.32,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 4241261,
          beatmapset_id: 2034265,
          user_id: 9562117,
          version: 'Insane',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.2,
          mode_int: 0,
          ar: 8.6,
          cs: 4,
          od: 8,
          hp: 6.2,
          hit_length: 177,
          total_length: 194,
          count_circles: 564,
          count_sliders: 214,
          count_spinners: 4,
          beatmapset: {
            id: 2034265,
            user_id: 9562117,
            ranked: 1,
            creator: 'Aranel',
            artist: 'boa',
            artist_unicode: 'bôa',
            title: 'Duvet',
            title_unicode: 'Duvet',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'FM',
        isLast: true,
        star: 5.2,
      },
      {
        code: 200,
        message: 'ok',
        data: {
          id: 3069278,
          beatmapset_id: 1414573,
          user_id: 11854343,
          version: 'Expert',
          ranked: 1,
          status: 'ranked',
          difficulty_rating: 5.68,
          mode_int: 0,
          ar: 9.3,
          cs: 4,
          od: 8.5,
          hp: 5,
          hit_length: 275,
          total_length: 276,
          count_circles: 851,
          count_sliders: 571,
          count_spinners: 1,
          beatmapset: {
            id: 1414573,
            user_id: 11854343,
            ranked: 1,
            creator: 'shoyeu',
            artist: 'Unlucky Morpheus',
            artist_unicode: 'Unlucky Morpheus',
            title: 'Black Pentagram',
            title_unicode: 'Black Pentagram',
            beatmaps: null,
          },
          mode: 'osu',
        },
        tag: 'TB',
        isLast: true,
        star: 5.68,
      },
    ],
    status: {
      isLoading: false,
      title: 'YHC S4 淘汰赛第三轮图池',
    },
    src: 'HD 4230631 4055401 4118513 4507262 4282790 4267493 4323255 NM 2979825 3489502 DT 3763548 3512086 4281786 FM 4263552 4183276 4241261 TB 3069278',
  },
};
export { testData };
